### ISSUE TITLE
breez_bridge.dart needs update

### ISSUE THREAD

**Issue by sagarsubedi** [breez/breez-sdk-flutter#1]
I see that there were changes made a couple weeks ago but some of the functions in the `breez_bridge.dart` file have not been updated as necessary. Here are the functions that my compiler errors out at:
- `Future<List<Payment>> listPayments()`. Here is the error: `The named parameter 'request' is required, but there's no corresponding argument. Try adding the required argument.`
- `Future<LnUrlCallbackStatus> lnurlWithdraw()`. The error is: `A value of type 'Future<LnUrlWithdrawResult>' can't be returned from the method 'lnurlWithdraw' because it has a return type of 'Future<LnUrlCallbackStatus>'.`
- `Future sweep()`. The error for this one is: `The named parameter 'request' is required, but there's no corresponding argument.
Try adding the required argument.`

**Comment by kumulynja** [comment]
I am encountering the same problem with version 0.2.5.

**Comment by erdemyerebasmaz** [comment]
@sagarsubedi @kumulynja 
There has been breaking changes between 0.2.4 to 0.2.5 and this flutter package has been published before those have been addressed on breez_bridge.dart. 

Please downgrade to 0.2.4 temporarily.

We're planning to release 0.2.6 this week that addresses these issues and introduces other breaking changes which will be documented on CHANGELOG.md. The necessary migration steps will also be documented.

Thanks

**Comment by roeierez** [comment]
@erdemyerebasmaz  I think we have an issue here: https://github.com/breez/breez-sdk-flutter/blob/main/ios/breez_sdk.podspec#L24 where it refers to 0.2.3 instead of 0.2.5

**Comment by erdemyerebasmaz** [comment]
Resolved with [Update Breez SDK Flutter package to version v0.2.7](https://github.com/breez/breez-sdk-flutter/commit/9629def110a9dd03413850a05e9709d3c9794b0d)
