### ISSUE TITLE
Flutter rust bridge issue when using bdk_flutter

### ISSUE THREAD

**Issue by yshwanth** [breez/breez-sdk-flutter#4]
flutter rust bridge for Breez plugin has 1.80.1, where as bdk_flutter has flutter_rust_bridge: ">1.82.3 <= 1.82.4". 
How do we resolve this ?

**Comment by erdemyerebasmaz** [comment]
> flutter rust bridge for Breez plugin has 1.80.1, where as bdk_flutter has flutter_rust_bridge: ">1.82.3 <= 1.82.4". 
> 
> How do we resolve this ?

Please test a variation of [this solution](https://github.com/breez/breez-sdk-flutter/pull/2#issuecomment-1774863798) using that range.
